### ISSUE TITLE
membership cordapp doesn't run on Corda Enterprise 4.1

### ISSUE THREAD

**Issue by countfloyd** [corda/corda-solutions#110]
I suspect because it's missing liquibase migration scripts:

```
[ERROR] 2019-07-10T15:10:12,661Z [main] internal.NodeStartupLogging.invoke - Could not create the DataSource: No migration defined for schema: com.r3.businessnetworks.membership.flows.bno.service.PendingMembershipRequestSchema v1: Could not create the DataSource: No migration defined for schema: com.r3.businessnetworks.membership.flows.bno.service.PendingMembershipRequestSchema v1 [errorCode=5k06pt, moreInformationAt=https://errors.corda.net/ENT/4.1/5k06pt] {}
net.corda.nodeapi.internal.persistence.CouldNotCreateDataSourceException: Could not create the DataSource: No migration defined for schema: com.r3.businessnetworks.membership.flows.bno.service.PendingMembershipRequestSchema v1
        at net.corda.node.internal.AbstractNodeKt.startHikariPool(AbstractNode.kt:1181) ~[corda-node-4.1.jar:?]
        at net.corda.node.internal.AbstractNode.startDatabase(AbstractNode.kt:830) ~[corda-node-4.1.jar:?]
        at net.corda.node.internal.Node.startDatabase(Node.kt:465) ~[corda-node-4.1.jar:?]
        at net.corda.node.internal.AbstractNode.start(AbstractNode.kt:345) ~[corda-node-4.1.jar:?]
        at net.corda.node.internal.Node.start(Node.kt:480) ~[corda-node-4.1.jar:?]
        at net.corda.node.internal.EnterpriseNode.start(EnterpriseNode.kt:189) ~[corda-node-4.1.jar:?]
        at net.corda.node.internal.NodeStartup.startNode(NodeStartup.kt:190) ~[corda-node-4.1.jar:?]
        at net.corda.node.internal.NodeStartupCli$runProgram$2.run(NodeStartup.kt:113) ~[corda-node-4.1.jar:?]
        at net.corda.node.internal.NodeStartup$initialiseAndRun$5.invoke(NodeStartup.kt:167) ~[corda-node-4.1.jar:?]
        at net.corda.node.internal.NodeStartup$initialiseAndRun$5.invoke(NodeStartup.kt:120) ~[corda-node-4.1.jar:?]
        at net.corda.node.internal.NodeStartupLogging$DefaultImpls.attempt(NodeStartup.kt:498) ~[corda-node-4.1.jar:?]
        at net.corda.node.internal.NodeStartup.attempt(NodeStartup.kt:120) ~[corda-node-4.1.jar:?]
        at net.corda.node.internal.NodeStartup.initialiseAndRun(NodeStartup.kt:166) ~[corda-node-4.1.jar:?]
        at net.corda.node.internal.NodeStartupCli.runProgram(NodeStartup.kt:111) ~[corda-node-4.1.jar:?]
        at net.corda.cliutils.CordaCliWrapper.call(CordaCliWrapper.kt:190) ~[corda-tools-cliutils-4.1.jar:?]
        at net.corda.cliutils.CordaCliWrapper.call(CordaCliWrapper.kt:156) ~[corda-tools-cliutils-4.1.jar:?]
        at picocli.CommandLine.execute(CommandLine.java:1056) ~[picocli-3.8.0.jar:3.8.0]
        at picocli.CommandLine.access$900(CommandLine.java:142) ~[picocli-3.8.0.jar:3.8.0]
        at picocli.CommandLine$RunLast.handle(CommandLine.java:1246) ~[picocli-3.8.0.jar:3.8.0]
        at picocli.CommandLine$RunLast.handle(CommandLine.java:1214) ~[picocli-3.8.0.jar:3.8.0]
        at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1122) ~[picocli-3.8.0.jar:3.8.0]
        at picocli.CommandLine.parseWithHandlers(CommandLine.java:1405) ~[picocli-3.8.0.jar:3.8.0]
        at net.corda.cliutils.CordaCliWrapperKt.start(CordaCliWrapper.kt:73) ~[corda-tools-cliutils-4.1.jar:?]
        at net.corda.node.Corda.main(Corda.kt:13) ~[corda-node-4.1.jar:?]
Caused by: net.corda.nodeapi.internal.persistence.MissingMigrationException: No migration defined for schema: com.r3.businessnetworks.membership.flows.bno.service.PendingMembershipRequestSchema v1
        at net.corda.nodeapi.internal.persistence.SchemaMigration.doRunMigration(SchemaMigration.kt:137) ~[corda-node-api-4.1.jar:?]
        at net.corda.nodeapi.internal.persistence.SchemaMigration.runMigration(SchemaMigration.kt:79) ~[corda-node-api-4.1.jar:?]
        at net.corda.nodeapi.internal.persistence.SchemaMigration.runMigration$default(SchemaMigration.kt:79) ~[corda-node-api-4.1.jar:?]
        at net.corda.nodeapi.internal.persistence.SchemaMigration.nodeStartup(SchemaMigration.kt:68) ~[corda-node-api-4.1.jar:?]
        at net.corda.node.internal.AbstractNodeKt.startHikariPool(AbstractNode.kt:1173) ~[corda-node-4.1.jar:?]
        ... 23 more
```

**Comment by manosbatsis** [comment]
Same on CE 4.2, should be able to add a PR shortly though:

```
[INFO ] 2019-10-06T22:05:39,564Z [main] hikari.HikariDataSource.<init> - HikariPool-1 - Starting... {}
[INFO ] 2019-10-06T22:05:39,924Z [main] hikari.HikariDataSource.<init> - HikariPool-1 - Start completed. {}
[ERROR] 2019-10-06T22:05:40,155Z [main] internal.NodeStartupLogging.invoke - Could not create the DataSource: No migration defined for schema: com.r3.businessnetworks.membership.flows.bno.service.PendingMembershipRequestSchema v1: Could not create the DataSource: No migration defined for schema: com.r3.businessnetworks.membership.flows.bno.service.PendingMembershipRequestSchema v1 [errorCode=5k06pt, moreInformationAt=https://errors.corda.net/ENT/4.2/5k06pt] {}
net.corda.nodeapi.internal.persistence.CouldNotCreateDataSourceException: Could not create the DataSource: No migration defined for schema: com.r3.businessnetworks.membership.flows.bno.service.PendingMembershipRequestSchema v1
	at net.corda.node.internal.AbstractNodeKt.startHikariPool(AbstractNode.kt:1210) ~[corda-node-4.2.jar:?]
	at net.corda.node.internal.AbstractNode.startDatabase(AbstractNode.kt:857) ~[corda-node-4.2.jar:?]
	at net.corda.node.internal.Node.startDatabase(Node.kt:491) ~[corda-node-4.2.jar:?]
	at net.corda.node.internal.AbstractNode.start(AbstractNode.kt:359) ~[corda-node-4.2.jar:?]
	at net.corda.node.internal.Node.start(Node.kt:506) ~[corda-node-4.2.jar:?]
	at net.corda.node.internal.EnterpriseNode.start(EnterpriseNode.kt:207) ~[corda-node-4.2.jar:?]
	at net.corda.node.internal.NodeStartup.startNode(NodeStartup.kt:190) ~[corda-node-4.2.jar:?]
	at net.corda.node.internal.NodeStartupCli$runProgram$2.run(NodeStartup.kt:113) ~[corda-node-4.2.jar:?]
	at net.corda.node.internal.NodeStartup$initialiseAndRun$5.invoke(NodeStartup.kt:167) ~[corda-node-4.2.jar:?]
	at net.corda.node.internal.NodeStartup$initialiseAndRun$5.invoke(NodeStartup.kt:120) ~[corda-node-4.2.jar:?]
	at net.corda.node.internal.NodeStartupLogging$DefaultImpls.attempt(NodeStartup.kt:498) ~[corda-node-4.2.jar:?]
	at net.corda.node.internal.NodeStartup.attempt(NodeStartup.kt:120) ~[corda-node-4.2.jar:?]
	at net.corda.node.internal.NodeStartup.initialiseAndRun(NodeStartup.kt:166) ~[corda-node-4.2.jar:?]
	at net.corda.node.internal.NodeStartupCli.runProgram(NodeStartup.kt:111) ~[corda-node-4.2.jar:?]
	at net.corda.cliutils.CordaCliWrapper.call(CordaCliWrapper.kt:190) ~[corda-tools-cliutils-4.2.jar:?]
	at net.corda.cliutils.CordaCliWrapper.call(CordaCliWrapper.kt:156) ~[corda-tools-cliutils-4.2.jar:?]
	at picocli.CommandLine.execute(CommandLine.java:1056) ~[picocli-3.8.0.jar:3.8.0]
	at picocli.CommandLine.access$900(CommandLine.java:142) ~[picocli-3.8.0.jar:3.8.0]
	at picocli.CommandLine$RunLast.handle(CommandLine.java:1246) ~[picocli-3.8.0.jar:3.8.0]
	at picocli.CommandLine$RunLast.handle(CommandLine.java:1214) ~[picocli-3.8.0.jar:3.8.0]
	at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1122) ~[picocli-3.8.0.jar:3.8.0]
	at picocli.CommandLine.parseWithHandlers(CommandLine.java:1405) ~[picocli-3.8.0.jar:3.8.0]
	at net.corda.cliutils.CordaCliWrapperKt.start(CordaCliWrapper.kt:73) ~[corda-tools-cliutils-4.2.jar:?]
	at net.corda.node.Corda.main(Corda.kt:13) ~[corda-node-4.2.jar:?]
Caused by: net.corda.nodeapi.internal.persistence.MissingMigrationException: No migration defined for schema: com.r3.businessnetworks.membership.flows.bno.service.PendingMembershipRequestSchema v1
	at net.corda.nodeapi.internal.persistence.SchemaMigration.doRunMigration(SchemaMigration.kt:137) ~[corda-node-api-4.2.jar:?]
	at net.corda.nodeapi.internal.persistence.SchemaMigration.runMigration(SchemaMigration.kt:79) ~[corda-node-api-4.2.jar:?]
	at net.corda.nodeapi.internal.persistence.SchemaMigration.runMigration$default(SchemaMigration.kt:79) ~[corda-node-api-4.2.jar:?]
	at net.corda.nodeapi.internal.persistence.SchemaMigration.nodeStartup(SchemaMigration.kt:68) ~[corda-node-api-4.2.jar:?]
	at net.corda.node.internal.AbstractNodeKt.startHikariPool(AbstractNode.kt:1202) ~[corda-node-4.2.jar:?]
	... 23 more

```

**Comment by manosbatsis** [comment]
Actually master seems to have this __partly__ fixed already:

https://github.com/manosbatsis/corda-solutions/tree/976e2abb5bdebf3841c8a2c74ede3a381fe08a3f/bn-apps/memberships-management/membership-service-contracts-and-states/src/resources/migration

**Comment by manosbatsis** [comment]
A workaround could be:

1. pickup the migration files from https://github.com/corda/corda-solutions/pull/136 
2. create a JAR with a migration folder containing the above fioles
3. deploy this JAR in the node’s cordapps folder
